version: '2'
services:

    db:
      image: mysql
      volumes:
        - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        - ./db:/var/lib/mysql:rw
      environment:
        - MYSQL_ROOT_PASSWORD=tictactoe
  
    restful:
      image: eboraas/phalcon
      volumes:
        - ./src:/var/www/phalcon
      ports:
        - "80:80"
      depends_on:
        - db
