
CREATE DATABASE IF NOT EXISTS `tictactoe` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `tictactoe`;


DROP TABLE IF EXISTS `games`;
CREATE TABLE `games` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `board` varchar(9) DEFAULT '         'COLLATE utf8_unicode_ci NOT NULL,
  `turn` ENUM('X','O') DEFAULT 'O',
  `status` ENUM('PROGRESS','WIN_X','WIN_O','DRAW') DEFAULT 'PROGRESS',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;